##-----------------
#hwi_oauth_redirect:
#    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
#    prefix:   /connect
#
#hwi_oauth_connect:
#    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
#    prefix:   /connect
#
#hwi_oauth_login:
#    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
#    prefix:   /login

# -------------- Securité  -------------------------------------------

csrf_token:
    path: /csrf_token
    controller: App\Controller\SecurityController::csrfToken
awid_register:
    path: /register
    controller: App\Controller\SecurityController::register

fos_user_registration_confirmed:
   path: /register/confirmed
   controller: App\Controller\SecurityController::confirmed

fos_user_security_login:
    path: /login
    controller: App\Controller\SecurityController::login


#    ----------------------------------------------------------------------
index:
    path: /
    controller: App\Controller\MainController::index

hello:
   path: /hello
   controller: App\Controller\MainController::hello

# -------------------- advertisement routes ----------------------------- #
add_advertisement:
    path: packet/add/{adverType}
    controller: App\Controller\AdvertisementController::addAdvertisement

delete_advertisement:
    path: packet/delete/{id}
    controller: App\Controller\AdvertisementController::deleteAdvertisement

update_advertisement:
    path: packet/update/{id}
    controller: App\Controller\AdvertisementController::updateAdvertisement

my_advertisements:
    path: packet/mine/{adverType}
    controller: App\Controller\AdvertisementController::getMyAdvertisements

all_advertisements:
    path: packet/all/{adverType}
    controller: App\Controller\AdvertisementController::getAllAdvertisement

show_advertisements:
    path: packet/show/{id}
    controller: App\Controller\AdvertisementController::showAdvertisement

#------------------------ Message Routes ----------------------------------- #

add_message:
    path: message/add/{toUserId}
    controller: App\Controller\MessageController::addMessage

send_message_from_detail:
    path : message/send/{toUserId}
    controller : App\Controller\MessageController::sendMessageFromDetail

messages_box:
    path: message/box
    controller: App\Controller\MessageController::getMessagesBox

received_message:
    path: message/received
    controller: App\Controller\MessageController::getReceivedMessage

sent_message:
    path: message/sent
    controller: App\Controller\MessageController::getSentMessage

show_message:
    path: message/show/{messageId}
    controller: App\Controller\MessageController::showMessage



#-------------------------------Information generale -------------- #

who_we_are:
    path: informations/whoarewe
    controller: App\Controller\InformationController::whoAreWe

how_it_works:
    path: informations/howItWorks
    controller: App\Controller\InformationController::howItWorks

objective:
    path: informations/objective
    controller: App\Controller\InformationController::objective

presentation:
    path: informations/presentation
    controller: App\Controller\InformationController::presentation

cgu:
    path: informations/cgu
    controller: App\Controller\InformationController::cgu

# --------------------- Dashboard  --------------------------------- #

dashboard:
    path: dashboard/index
    controller: App\Controller\DashboardController::index
