index:
    path: /
    controller: App\Controller\MainController::index

# -------------------- advertisement routes ----------------------------- #
add_advertisement:
    path: advertisement/add/{adeverType}
    controller: App\Controller\AdvertisementController::addAdvertisement

delete_advertisement:
    path: advertisement/delete/{id}
    controller: App\Controller\AdvertisementController::deleteAdvertisement

update_advertisement:
    path: advertisement/update/{id}
    controller: App\Controller\AdvertisementController::updateAdvertisement

get_my_advertisements:
    path: advertisement/mine
    controller: App\Controller\AdvertisementController::getMyAdvertisements

get_all_advertisements:
    path: advertisement/all
    controller: App\Controller\AdvertisementController::getAllAdvertisement

