index:
    path: /
    controller: App\Controller\MainController::index

# -------------------- advertisement routes ----------------------------- #
add_advertisement:
    path: advertisement/add/{adverType}
    controller: App\Controller\AdvertisementController::addAdvertisement

delete_advertisement:
    path: advertisement/delete/{id}
    controller: App\Controller\AdvertisementController::deleteAdvertisement

update_advertisement:
    path: advertisement/update/{id}
    controller: App\Controller\AdvertisementController::updateAdvertisement

my_advertisements:
    path: advertisement/mine/{adverType}
    controller: App\Controller\AdvertisementController::getMyAdvertisements

all_advertisements:
    path: advertisement/all/{adverType}
    controller: App\Controller\AdvertisementController::getAllAdvertisement


#------------------------ Message Routes ----------------------------------- #

add_message:
    path: message/add/{toUserId}
    controller: App\Controller\MessageController::addMessage

received_message:
    path: message/received
    controller: App\Controller\MessageController::getReceivedMessage

sent_message:
    path: message/sent
    controller: App\Controller\MessageController::getSentMessage

show_message:
    path: message/show/{messageId}
    controller: App\Controller\MessageController::showMessage


