##-----------------
#hwi_oauth_redirect:
#    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
#    prefix:   /connect
#
#hwi_oauth_connect:
#    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
#    prefix:   /connect
#
#hwi_oauth_login:
#    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
#    prefix:   /login


#    ----------------------------------------------------------------------
index:
    path: /
    controller: App\Controller\MainController::index

# -------------------- advertisement routes ----------------------------- #
add_advertisement:
    path: advertisement/add/{adverType}
    controller: App\Controller\AdvertisementController::addAdvertisement

delete_advertisement:
    path: advertisement/delete/{id}
    controller: App\Controller\AdvertisementController::deleteAdvertisement

update_advertisement:
    path: advertisement/update/{id}
    controller: App\Controller\AdvertisementController::updateAdvertisement

my_advertisements:
    path: advertisement/mine/{adverType}
    controller: App\Controller\AdvertisementController::getMyAdvertisements

all_advertisements:
    path: advertisement/all/{adverType}
    controller: App\Controller\AdvertisementController::getAllAdvertisement


#------------------------ Message Routes ----------------------------------- #

add_message:
    path: message/add/{toUserId}
    controller: App\Controller\MessageController::addMessage

received_message:
    path: message/received
    controller: App\Controller\MessageController::getReceivedMessage

sent_message:
    path: message/sent
    controller: App\Controller\MessageController::getSentMessage

show_message:
    path: message/show/{messageId}
    controller: App\Controller\MessageController::showMessage

#-------------------------------Information generale -------------- #

who_we_are:
    path: informations/whoarewe
    controller: App\Controller\InformationController::whoAreWe

how_it_works:
    path: informations/howItWorks
    controller: App\Controller\InformationController::howItWorks

objective:
    path: informations/objective
    controller: App\Controller\InformationController::objective

presentation:
    path: informations/presentation
    controller: App\Controller\InformationController::presentation

cgu:
    path: informations/cgu
    controller: App\Controller\InformationController::cgu
